### ISSUE TITLE
Workflows don't use executable paths specified in config file.

### ISSUE THREAD

**Issue by kescobo** [Klepac-Ceraj-Lab/snakemake_workflows#26]
There's a section in `config_template.yaml`:

```yaml
executables:
    kneaddata: kneaddata
    metaphlan2: metaphlan2
    humann2: humann2
    diamond: diamond
```

but these aren't actually used in the workflows.
