### ISSUE TITLE
Add nthreads argument to kneaddata rule

### ISSUE THREAD

**Issue by kescobo** [Klepac-Ceraj-Lab/snakemake_workflows#39]
Currently single-threaded

**Comment by kescobo** [comment]
@denizeu 

- Get `--threads` (kneaddata), `--nprocs` (`metaphlan`) etc from cluster config
- Need also to set default if there is no cluster config

**Comment by kescobo** [comment]
https://snakemake.readthedocs.io/en/stable/executing/cluster.html

Looks like we can just set `resources` for the rules that we need it for, and use the `--default-resources` flag for others.

```
--default-resources [NAME=INT ...], --default-res [NAME=INT ...]
                        Define default values of resources for rules that do not
                        define their own values. In addition to plain integers,
                        python expressions over inputsize are allowed (e.g.
                        '2*input.size_mb').When specifying this without any arguments
                        (--default-resources), it defines
                        'mem_mb=max(2*input.size_mb, 1000)'
                        'disk_mb=max(2*input.size_mb, 1000)' i.e., default disk and
                        mem usage is twice the input file size but at least 1GB.In
                        addition, the system temporary directory (as given by
                        $TMPDIR, $TEMP, or $TMP) is used for the tmpdir resource. The
                        tmpdir resource is automatically used by shell commands,
                        scripts and wrappers to store temporary data (as it is
                        mirrored into $TMPDIR, $TEMP, and $TMP for the executed
                        subprocesses). If this argument is not specified at all,
                        Snakemake just uses the tmpdir resource as outlined above.
                        (default: None)
```

**Comment by kescobo** [comment]
My thinking is that we add something to the `config` that's something like:

```
rule_resources:
    kneaddata:
        threads: 8
        memory: 8000
    humann:
# .... etc
```

Then, in the `kneaddata` rule, we'd have something like

```
rule: kneaddata
#... inputs/ outputs
    resources:
        threads: config["rule_resources"]["kneaddata"]["threads"]
#... etc
     run:
         shell("kneaddata ... --threads {resources.threads} ...")
```
